;; -*- lexical-binding: t; -*-

;; load paths settings from paths.el, generated by the Makefile
(load (expand-file-name "paths.el" user-emacs-directory))

;; add custom features directory to Emacs load path
(add-to-list 'load-path nxt/custom-features-directory)

;; require the features file.
(require 'init-features)

